---
title: "慢性肾病管理"
subtitle: "数据分析与结果洞察"
date: "2021年8月"
output:
  slidy_presentation: default
  ioslides_presentation:
    widescreen: yes
    smaller: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F,
                      cache = T)
```

```{r Packages.}
library(tidyverse)
library(lubridate)
library(readxl)
library(nlme)
library(sjPlot)
library(glmmTMB)
library(doParallel)
library(scales)
library(patchwork)
```

```{r Initiate parallel processing}
all_cores <- detectCores(logical = FALSE)

registerDoParallel(cores = all_cores)
```


```{r Helper functions}
# Read all excel sheets. 
source("excel_all_sheets.R")
```

```{r Chinese character setup}
theme <- theme_get()
#using the Chinese fonts you have, check it with font book.  
theme$text$family <- "STFangsong"
theme_set(theme)
```

```{r year name}
year <- 2012:2020
```

```{r Read data include=FALSE}
# Read 9 excel sheets and return 9 data frames.  
my_dat <- read_excel_allsheets(filename = 'data/raw.xlsx')

# For each data frame
# Loop to change wide format to wide
# Combine data by year. 
total <- data.frame()

for (i in 1:length(my_dat)) {
    
    # Label year for each data frame
    my_dat[[i]]$year <- year[i]
    
    # Fill each row with HIS id. 
    # A vector
    l <- vector()
    # Loop to fill HIS. 
    for (j in 1:nrow(my_dat[[i]])) {
        if(!is.na(my_dat[[i]]$`患者His号（完整10位数）`[j])){
            l[j] = my_dat[[i]]$`患者His号（完整10位数）`[j]
            }else{
                l[j] = l[j-1]
            }
    }
    
    # New HIS id and remove old HIS
    my_dat[[i]]$HIS_new<-l

    # pt info table
    # Col 2-9 as pt info. 
    # Col ncol(df) as row-filled HIS id. 
    pt_info <- my_dat[[i]][, c(2:9, ncol(my_dat[[i]]))]
    # Remove rows of all NAs. 
    pt_info <- pt_info %>%
        filter_all(any_vars(!is.na(.)))
    
    #Column rename of pt info
    colnames(pt_info) <- c("Gender", "Age", "HIS",
                           "Doctor", "ICD", "Dx",
                           "In-Patient", "Follow_up", "HIS_new")
    
    # Cols from col 10 as data
    # Data labeled with HIS id.
    # Col 4: HIS ID
    # Col 10 to end: data and date
    pt_data <- my_dat[[i]][, c(10:ncol(my_dat[[i]]))]
    # HIS_new as first column
    pt_data <- pt_data %>%
        select(HIS_new, everything())

    # Rearrange each pt_data to long format
    dat <- data.frame()
    for(k in 1:((ncol(pt_data)-1)/2)) {
        if(2*k + 1 <= ncol(pt_data)) {
            tmp <- pt_data[, c(1, (2*k):(2*k + 1), ncol(pt_data))]
            tmp$name <- colnames(tmp)[2]
            colnames(tmp)[2:3] <- c("data", "date")
            dat <- rbind(dat, tmp)
        }
    }
    # In each year
    # Join dat (long format pts data)
    # With pt_info
    dat <- dat %>%
        right_join(pt_info, by = "HIS_new")
    
    # Combine data of 9 years
    total <- rbind(total, dat)
}
```

```{r Data cleaning}
# Date format
total$date <- ymd(total$date)
# Remove old HIS id. 
total <- total %>%
    select(-HIS)
# Remove NAs of redudant pt_info
total <- total %>%
    filter(!is.na(Gender) & 
               !is.na(Age) &
               !is.na(Doctor))
# Remove 'doctor', 'Follow_up' columns
# All entries in 'Follow_up' is high
total <- total %>%
    select(-Doctor, -Follow_up)

# Drop NAs
total <- total %>%
    filter(!is.na(data))
# Remove repeated entries. 
total <- distinct(total)
```

```{r Correct the age}
# Age is kept as the CURRENT 2020 age
# for Age in 2019, need to minus 1. 
# For each HIS id, get the year change from a year to 2020
total$year_change <- 2020 - total$year
# Substract Age 2020 with year change. 
total$Age <- total$Age - total$year_change
```

```{r Consolidate ICD entries, eval=FALSE, include=FALSE}
#Consolidate ICD code
#icd <- table(total$ICD)
#write.csv(icd, "icd.csv")
```


```{r Outlier removal TG}
outlier <- total %>%
    filter(HIS_new %in% "0000373621" & 
               name %in% "甘油三酯" & 
               year %in% "year2020")

total[total$HIS_new == "0000373621" & 
               total$name == "甘油三酯" & 
               total$year == 2020 & 
          total$data == 22.29, ]$data <- median(outlier$data)
```

```{r Outlier removal Creatine}
outlier <- total %>%
    filter((HIS_new %in% "0005316026") & 
               name %in% "血清肌酐" & 
               year %in% 2013) %>%
    arrange(desc(data))

total[total$HIS_new == "0005316026" & 
               total$name == "血清肌酐" & 
               total$year == 2013 & 
          total$data == 25938.0, ]$data <- median(outlier$data)

outlier <- total %>%
    filter((HIS_new %in% "0000701411") & 
               name %in% "血清肌酐" & 
               year %in% 2013) %>%
    arrange(desc(data))

total[total$HIS_new == "0000701411" & 
               total$name == "血清肌酐" & 
               total$year == 2013 & 
          total$data == 23239.0, ]$data <- median(outlier$data)

outlier <- total %>%
    filter((HIS_new %in% "0005922995") & 
               name %in% "血清肌酐" & 
               year %in% 2015) %>%
    arrange(desc(data))


total[total$HIS_new == "0005922995" & 
               total$name == "血清肌酐" & 
               total$year == 2015 & 
          total$data == 1997.0, ]$data <- median(outlier$data)
```


$$
\text{eGFR}_{\text{male}} = 186 \times \text{Serum Cr}^{-1.154}\times \text{Age}^{-0.203} \\

\text{eGFR}_{\text{female}} = 186 \times \text{Serum Cr}^{-1.154}\times \text{Age}^{-0.203} \times {0.742}
$$
```{r Calculate eGFR}
# Select all creatine 
cr <- total %>%
  filter(name %in% "血清肌酐")
# eGFR function based on modified MDRD in China
# Formula above. 
eGFR <- function(data = cr) {
  if(cr$Gender %in% "男") {
    # male formula
    eGFR <- 88.41 * 186 * (cr$data)^(-1.154) * (cr$Age)^(-0.203)
  }else{
    # female formula
    eGFR <- 88.41 * 186 * (cr$data)^(-1.154 )* (cr$Age)^(-0.203) * 0.742
  }
}

cr$name <- "eGFR"
cr$data <- eGFR(data = cr)

# row combine of cr to total
# eGFR as data in column 'name'. 
total <- rbind(total, cr)

# Remove eGFR in raw data, 
# which is missed for most cases. 
total <- total %>%
  filter(! name %in% "估算肾小球滤过率")
```

```{r remove BP and weight}
# BP weight data only available in 2020
# Excluded from longitudinal analysis
# Included in 2020 cross-sectional analysis. 
# Longi_total as data set for longitudinal analysis. 
longi_total <- total %>%
    filter(!name %in% "收缩压" &
               !name %in% "舒张压" &
               !name %in% "体重")
```

```{r annual mean by metrics}
# For each HIS id, 
# Calculate the annual mean of each metric
annual_mean <- longi_total %>%
    group_by(HIS_new, year, name) %>%
    summarise(mu = mean(data, na.rm = TRUE))
```

```{r Plot annual mean, fig.width=8, fig.asp=.618}
# For each HIS id, 
# Plot the annual mean of each metric
# Facet by metric. 
ggplot(annual_mean) + 
    geom_line(aes(x = year, y = mu, 
                  colour = name, 
                  group = HIS_new), 
              alpha = .8) + 
    facet_wrap(name~.,scales = "free") 
```

```{r}
# Read ICD.xlsx
icd <- read_excel("icd.xlsx")
# Select two columns
icd <- icd[, c(2:3)]

# Select total data in 2020
# Only 2020 data has ICD entries
total_2020 <- total %>%
  filter(year %in% 2020)

# Join icd with total_2020
# In total_2020: use column 'ICD'; 
# In icd, use column 'RAW'. 
total_2020 <- total_2020 %>%
  left_join(icd)

# Select HIS_new and new_icd columns
# This is a unified icd diagnosis for each patient in each year
icd <- total_2020 %>%
  select(HIS_new, NewICD)

# Join ICD with total dataset
total <- total %>%
  left_join(icd, by = "HIS_new")

# Drop NAs in NewICD
total <- total %>%
  filter(! is.na(NewICD))

# Remove column 'ICD', 'Dx', 'year_change'
total <- total %>%
  select(-ICD, -Dx, -year_change)
```

```{r}
# Subset to get all eGFR
egfr <- total %>%
  filter(name %in% "eGFR")

egfr <- distinct(egfr)

# Select HIS_new, data and date
egfr <- egfr %>%
  select(HIS_new, data, date)

# Join egfr by HIS_new and date
# With total
total <- merge(total, egfr, by.x = c("HIS_new", "date"), 
               by.y = c("HIS_new", "date"))
# eGFR as a column variable. 
# Notice eGFR also as data in column 'data'. 

# Rename 'total'. 
colnames(total) <- c("HIS_new", "date", "data", "year", 
                     "name", "Gender", "Age", "In-Patient", 
                     "NewICD", "eGFR")

# CKD stage by eGFR. 
total$stage <- cut(total$eGFR, 
                   breaks = c(0, 15, 29, 59, 89, 2000), 
                   labels = c("ESRD", "CKD4", "CKD3", 
                              "CKD2", "Normal"))

total %>%
  filter(name %in% "eGFR") %>%
  distinct() %>%
  filter(! NewICD %in% "CKD1" &
           ! NewICD %in% "CKD2" &
           ! NewICD %in% "CKD3"&
           ! NewICD %in% "CKD4") %>%
  ggplot() + 
  geom_line(aes(x = date, y = data, 
                colour = NewICD, 
                group = HIS_new)) + 
  facet_grid(NewICD~.)

```


## On target rate of key metrics. 

```{r Normal table.}
# Read normal table. 
normal <- read_csv("data/normal.csv")
metric_CHN <- c("白蛋白", "血磷", "C-反应蛋白",
                "总胆固醇", "甘油三酯", "低密度脂蛋白",
                "高密度脂蛋白", "尿酸-男性", "尿酸-女性",
                "收缩压", "舒张压", "血红蛋白-男性", "血红蛋白-女性")
# Assign metric in Chinese
normal$metric_CHN <- metric_CHN
# Remove a column. 
normal<- normal[, -1]
```

```{r}
m <- c("甘油三酯", "尿酸", "血红蛋白", "白蛋白")
```

```{r triglyceride TG}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[1]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[1])) %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[1, 3], 
                                   normal_tmp[1, 4], 
                                   normal_tmp[1, 5],
                                   normal_tmp[1, 6]), 
                        labels = c("Low", "Normal", "High"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = -0.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 0.5)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of triglyceride by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

```{r UA male}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[2]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[2])) %>%
  filter(Gender %in% "男") %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[1, 3], 
                                   normal_tmp[1, 4], 
                                   normal_tmp[1, 5],
                                   normal_tmp[1, 6]), 
                        labels = c("Low", "Normal", "High"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = 1.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of uric acid of male by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

```{r UA female}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[2]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[2])) %>%
  filter(Gender %in% "女") %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[2, 3], 
                                   normal_tmp[2, 4], 
                                   normal_tmp[2, 5],
                                   normal_tmp[2, 6]), 
                        labels = c("Low", "Normal", "High"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = 1.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of uric acid of female by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

```{r Hb male}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[3]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[3])) %>%
  filter(Gender %in% "男") %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[1, 3], 
                                   normal_tmp[1, 4], 
                                   normal_tmp[1, 5],
                                   normal_tmp[1, 6]), 
                        labels = c("Low", "Normal", "High"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = 1.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of homoglobin of male by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

```{r Hb female}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[3]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[3])) %>%
  filter(Gender %in% "女") %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[2, 3], 
                                   normal_tmp[2, 4], 
                                   normal_tmp[2, 5],
                                   normal_tmp[2, 6]), 
                        labels = c("Low", "Normal", "High"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = 1.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of homoglobin of female by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

```{r albumin}
# Select normal table triglyceride. 
normal_tmp <- normal %>%
  filter(str_detect(metric_CHN, m[4]))
# Subset TG from total
total_tmp <- total %>%
  filter(str_detect(name, m[4])) %>%
  # Remove repeated rows. 
  distinct() %>%
  # For each case;
  # Calculate the mean TG in that year. 
  group_by(HIS_new, year, stage) %>%
  summarise(mu = mean(data))

# Cut label by the normal table
total_tmp$target <- cut(total_tmp$mu, 
                        breaks = c(normal_tmp[1, 3], 
                                   normal_tmp[1, 4], 
                                   normal_tmp[1, 5],
                                   normal_tmp[1, 6]), 
                        labels = c("Low", "Normal", "Normal"))

tmp_test <- total_tmp %>%
  group_by(year, stage, target) %>%
  summarise(n = n()) %>%
  mutate(n_sum = sum(n)) %>%
  mutate(pct = n/sum(n)) %>%
  drop_na() %>%
  filter(target %in% "Normal")

ggplot(tmp_test, aes(x = factor(year), 
               y = pct)) + 
  geom_line(aes(group = stage, 
               colour = stage), 
            size = 4, 
            alpha = 0.8)+ 
  geom_point(colour = "grey", 
             size = 3) + 
  geom_text(aes(label = percent(pct, 2), 
                colour = stage), 
            vjust = 1.5,
            show.legend = FALSE) + 
  geom_text(aes(x = factor(year), y = 0.05, label = n_sum), 
            size = 3, 
            colour = "grey1") + 
  coord_cartesian(ylim = c(0, 1)) + 
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), 
                     labels = percent_format(1)) + 
  facet_grid(stage~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2, 
                        end = 0.8) + 
  labs(x = "Year", y = "Percentage %", 
       title = "On-target rate of albumin of  by CKD stage.") +
  theme(panel.grid.minor = element_blank())
```

## Longitudinal analysis

### Data selection by etiology. 


```{r}
total %>%
  filter(name %in% "eGFR") %>%
  distinct() %>%
  filter(! NewICD %in% "CKD1" &
           ! NewICD %in% "CKD2" &
           ! NewICD %in% "CKD3"&
           ! NewICD %in% "CKD4") %>%
  filter(! NewICD %in% "Diabetic nephritis" & 
           ! NewICD %in% "glomerular" & 
           ! NewICD %in% "Nephrosis") %>%
  ggplot() + 
  geom_point(aes(x = date, y = data, 
                colour = NewICD), 
             alpha = 0.5) + 
  geom_smooth(aes(x = date, y = data), 
              method = "lm", 
              colour = "orange", 
              size = 1, 
              se = FALSE) + 
  facet_grid(NewICD~.) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2)
```
Different slope and intercept
Repeated measurement of one case. 

## Longitudinal analysis. 
### Generalized linear mixed effect model. 

```{r}
tmp <- total %>%
  select(HIS_new, date, NewICD, eGFR) %>%
  distinct() %>%
  filter(!NewICD %in% "Diabetic nephritis" &
           !NewICD %in% "glomerular"  &
           !NewICD %in% "Nephrosis") %>%
  filter(! NewICD %in% "CKD1" &
           ! NewICD %in% "CKD2" &
           ! NewICD %in% "CKD3"&
           ! NewICD %in% "CKD4") 
```




```{r}
egfr_mixed1 <- lmer(eGFR ~ 1 + date + (1|HIS_new), 
                data = tmp)
```


```{r}
egfr_mixed1
```

```{r}
summary(egfr_mixed1)
```

```{r}
egfr_mixed2 <- lmer(eGFR ~ 1 + date + (date|HIS_new), 
                data = tmp)
```


```{r}
egfr_mixed2
```

```{r}
summary(egfr_mixed2)
```

```{r}
anova(egfr_mixed1, egfr_mixed2)
```


```{r}
plot_model(egfr_mixed2, type = "re", show.values = TRUE)
```


```{r}
tmp$pred <- predict(egfr_mixed2)

ggplot(tmp) + 
  geom_line(aes(x = date, y = pred, 
                group = HIS_new, 
                colour = NewICD)) + 
  scale_color_viridis_d(option = "D", 
                        begin = 0.2)
```


## Current status-quo--2020 crosssectional. 
### PCA and k-means clustering

```{r}
tmp <- total %>%
  filter(year %in% 2020) %>%
  filter(!name %in% "eGFR") %>%
  select("HIS_new", "data", "name", "Gender", "Age") %>%
  distinct() %>%
  group_by(HIS_new, name) %>%
  summarise(mu = mean(data)) %>%
  pivot_wider(names_from = name, 
              values_from  = mu) %>%
  select(-'血清肌酐') %>%
  drop_na()

```

```{r}
# Total within-groups sum of squares
tot.within.ss = numeric(10)
for (i in 1:10){
  set.seed(38360)
  tot.within.ss[i] = kmeans(scale(tmp[, c(2:8)]), i)$tot.withinss
}

# Plot total within-groups sum of squares
plot(1:10, tot.within.ss,
     main = "Total within-group sum of squares against cluster count",
     xlab = "Cluster count", ylab = "Total within-group sum of squares", type = "b")
```

```{r}
c1 <- kmeans(scale(tmp[, c(2:8)]), 4)

dat <- data.frame(c1$centers)

dat$group <- c("group1", "group2", "group3", "group4")

dat <- dat %>%
  pivot_longer(-group, values_to = "value", names_to = "metrics") 

g1 <- ggplot(dat) + 
  geom_col(aes(x = metrics, y = value, 
               fill = metrics)) + 
  facet_grid(group~.) + 
  labs(title = "患者特征肖像")

g1
```


```{r}
m <- scale(tmp[, c(2:8)])

pca.out <- prcomp(m)

pca.df <- pca.out$rotation

load <- m %*% t(pca.df)

colnames(load) <- paste0("PC", c(1:7))

load <- as.data.frame(load)

load <- cbind(load, factor(c1$cluster))

pca.df <- as.data.frame(pca.df)

pca.df$metric <- c("TG", "UA", "Hb",
                   "Alb", "SBP", "DBP", "Weight")


pca.df <- pca.df %>%
  select(metric, PC1, PC2) 


g2<- ggplot(data = load) + 
  geom_point(aes(x = PC1, y= PC2, 
                 colour = load$`factor(c1$cluster)`),
             size = 4, 
             alpha= 0.8)  + 
  geom_text(data = pca.df, 
               aes(x = PC1* 3.1, y = PC2* 3.1, 
                   label = metric), 
               size = 5, 
            vjust = -0.5, 
            hjust = 0.5) + 
  geom_segment(data = pca.df, 
               aes(x = 0, xend = PC1* 3, 
                   y = 0, yend = PC2* 3), 
               arrow = arrow(), 
               size = 0.2,
               colour = "steelblue") + 
  labs(title = "Patient cluster and key management --PCA analysis",
       x = "", 
       y = "") + 
  scale_color_viridis_d(option = "plasma", 
                        begin = 0.1) + 
  theme(panel.backgroun = element_blank()) 
  
g2
```

```{r}
g1 + g2
```

